name: Test Build Script

on:
  repository_dispatch:
    types: ["publish:build"]

jobs:
  # Here we will run the versioning script and then upload the package.json
  # as an artificat.  In the build steps on the matrix, we can download this
  # file after checking out the repo and before installing dependencies.
  prepare:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Clone the repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Install dependencies
        run: npm install

      - name: Set the build version
        run: npm run version:build

      - name: Upload version
        uses: actions/upload-artifact@v2
        with:
          name: package-json
          path: package.json
          retention-days: 1

  # This depends on the prepare step so these won't trigger until that
  # step is complete.  We could even check an success() method to make
  # sure everything is fine before we proceed.
  publish:
    needs: [prepare]
    strategy:
      matrix:
        os: ["ubuntu-16.04", "ubuntu-latest", "ubuntu-20.04"]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Clone the repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Download package artifact
        uses: actions/download-artifact@v2
        with:
          name: package-json

      - name: Install dependencies
        run: npm install

      - name: Print Build Version
        run: npm run publish
